### ISSUE TITLE
Zero interaction with development build / Typescript types

### ISSUE THREAD

**Issue by ottbalazs01** [Countly/countly-sdk-react-native-bridge#115]
I'm using development build and when I tried to integrate this package I had to see that nothing happened. I couldn't see any active users, or send events either. 

The other problem that I had, that there are no typescript type declarations. This also made my debugging hours longer, cause I had to find everything in the installed package.

**Comment by ArtursKadikis** [comment]
Hello, If you would enable the SDK logs the they should show a better picture of what the problem is.

Here you can find how to enable it:
https://support.count.ly/hc/en-us/articles/360037813231-React-Native-Bridge-#enable-logging

The recommended debugging flow can be found here:
https://support.count.ly/hc/en-us/articles/900000908046-Getting-started-with-SDKs#how-to-validate-your-countly-integration

TypeScript bindings is a thing that we are working towards.

For help with your integration we recommend posting here:
https://support.count.ly/hc/en-us/community/topics

Or even joining our slack group to seek help there:
https://slack.count.ly/
