### ISSUE TITLE
Error: Permission is only granted to system apps

### ISSUE THREAD

**Issue by ahmetkuslular** [Countly/countly-sdk-react-native-bridge#228]
```
Error: Permission is only granted to system apps [ProtectedPermissions]
      <uses-permission android:name="android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS" android:maxSdkVersion="30" />
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
     Explanation for issues of type "ProtectedPermissions":
     Permissions with the protection level signature, privileged or
     signatureOrSystem are only granted to system apps. If an app is a regular
     non-system app, it will never be able to use these permissions.
```

When I try to get build on android, I get an error like this.

 "react": "18.2.0",
 "react-native": "0.72.3",

**Comment by ijunaid** [comment]
Hello @ahmetkuslular,
Thanks for reporting this issue, 
It is due to some linter options added in the new Android Studio version.
I can still compile/run the project with this linter error.

You can also remove this error in Android Studio Settings
- Windows: 
File -> Settings -> Editor -> Inspections
Under 'Android Lint', locate 'Using system app permission'. Either uncheck the checkbox or choose a Severity lower than Error.

- Mac:
Android -> Settings -> Editor -> Inspections
Under 'Android Lint: Correctness', locate 'Using system app permission'. Either uncheck the checkbox or choose a Severity lower than Error.
I have added the screenshot of Mac Android Studio settings:
![AndroidStudio_Mac_Linter_Settings](https://github.com/Countly/countly-sdk-react-native-bridge/assets/4931668/b376b0b3-8c37-4b2f-b7e4-95f5623c8e7d)

**Comment by turtledreams** [comment]
Hi, 
If you are manually building instead of using the Android Studio then you would have to add a lint option in your build.gradle:
```
android {
    // ...
    lintOptions {
        // setting it to warning instead of error
        warning 'ProtectedPermissions'
    }
}
```
You can read more about the lintOptions from here: https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/LintOptions
