### ISSUE TITLE
Message from Google Play: Your app is vulnerable to Intent Redirection

### ISSUE THREAD

**Issue by jan-timpe** [Countly/countly-sdk-react-native-bridge#27]
I submitted my app update to Google Play and received a message that my app is vulnerable to Intent Redirection. I'm still waiting on additional details from the Google Play Developer Support team, but the only change to my app was the addition of Countly analytics.

I followed the setup instructions here: [React Native Bridge](https://support.count.ly/hc/en-us/articles/360037813231-React-Native-Bridge-)

Countly version: `20.4.7`

I don't know much about this vulnerability, but I'm happy to provide any additional information to help debug the issue.

**Comment by ijunaid** [comment]
Would you please share some more detail about the message you have received?
Check your [Play Console](https://play.google.com/apps/publish), there could be some additional information about vulnerabilities, Like information about vulnerable classes, etc.

**Comment by raynormw** [comment]
Hi, my apps also affected with this issue after countly integration..

Are this SDK already on progress with issue? Because i check the SDK for Android already got fixed in this commit:
https://github.com/Countly/countly-sdk-android/commit/c2d68dc17cce3227158ad9201e0e92682a4c470a

Looking for your reply, thank you.

**Comment by ijunaid** [comment]
@raynormw this issue is fixed will be available in the next release.
 Most probably the next release will be next week.

**Comment by socialcode-rob1** [comment]
Please re-open.

This issue seems to have had a resolution included in 20.11.0 but later reverted in 20.11.1+
I've been attempting to release with v20.11.2 and Google continues to decline my release package due to the same error.

`ly.count.android.sdk.messaging.CountlyPush$NotificationBroadcastReceiver.onReceive`

If anyone has been able to release, with 20.11.1+ 
What am I missing?

Thank you.

**Comment by ijunaid** [comment]
So with 20.11.0 you are able to publish the release and now with 20.11.2 Google declines your release with the same vulnerable intent redirection message?

Would you please share the full message you have received from google?
In your Play Console, there could be some additional information about vulnerabilities, Like information about vulnerable classes, etc.'

**Comment by socialcode-rob1** [comment]
Hi @ijunaid 

I mentioned `20.11.0` because this thread/issue seems to claim that a resolution was implemented according to Google's **Remediation for Intent Redirection Vulnerabiliy**, although when I tried yesterday with 20.11.0 and it failed as well.
ref: https://support.google.com/faqs/answer/9267555 

Message I received from Google when attempting to release with... either `20.4.9`, `20.11.0` or `20.11.2

`ly.count.android.sdk.messaging.CountlyPush$NotificationBroadcastReceiver.onReceive`

Previously we were able to release with `20.4.9`, it wasn't until after ~Dec 16th that Google started complaining about the library.

**Comment by ArtursKadikis** [comment]
Thanks for letting us know, we'll look more into this.

**Comment by iartem** [comment]
@socialcode-rob1 @raynormw @jan-timpe Hi 👋 
Could you confirm that our latest SDK update fixes it for you or post your dependencies list otherwise?

**Comment by ArtursKadikis** [comment]
Closing this as the issue should be solved.
